### ISSUE TITLE
Broken in clang

### ISSUE THREAD

**Issue by aaron-michaux** [davidstone/std_module#1]
The following code:

```
import std_module;

int main() { std::cout << "Hello Modular World!\n"; }
```

Produces this as output (in the terminal) !
```
0x402004
```

Clang 16.0.2

This is using System (debian bullseye) libstdc++. When using `-stdlib=libc++`, I get this:

```
hello_modular_world.cc:5:24: error: explicit specialization of 'char_traits<char>' must be imported from module 'std.string.__string.char_traits' before it is required
int main() { std::cout << "Hello Modular World!\n"; }
```

**Comment by davidstone** [comment]
Thanks for the report. Overloaded operators don't work that well in this attempt at modularization, so in those cases you'll need to do something like

```cpp
#include <std_module/prelude.hpp>
#include <iostream>

import std_module;
```

The weird runtime output you were seeing is because the `char *` overload wasn't found, but the general pointer overload was, so `"Hello Modular World!\n"` was printed as a pointer instead of a string.

I don't really think that this is something I can reasonably fix on my end without causing other strange issues or being a ton of work to try to keep up with, so it's just something we'll have to live with until we get `import std`. That is progressing in libc++: https://libcxx.llvm.org/Modules.html. I am not aware of progress in libstdc++.

**Comment by davidstone** [comment]
I was able to get this to work properly for libstdc++. https://github.com/davidstone/std_module/commit/e2921df601257e8dadc50c2f86f981a9b4d77b35
